project:
  type: website
  resources:
      - "keybase.txt"

website:
  title: "Old Huron Archive"
  site-url: https://old-huron-archive.netlify.app
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - posts.qmd
    right:
      - icon: rss
        href: posts.xml

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
