project:
  type: website
  resources:
      - "keybase.txt"

website:
  title: "Old Huron Archive"
  site-url: https://old-huron-archive.netlify.app
  image: img/ViktorHaag.png

  navbar:
    logo: img/ViktorHaag.png
    right:
      - about.qmd
      - icon: rss
        href: posts.xml

  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - text: "Home"
        file: index.qmd
      - text: "Blog"
        file: posts.qmd
      - section: Eagle Pass
        contents:
            - ep/index.qmd
            - ep/player-guide.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
