baseURL = "https://old-huron-archive.netlify.com/"
languageCode = "en-ca"
title = "Old Huron Archive"

rssLimit = "10"
sectionPagesMenu = "main"

[author]
    name = "Viktor Haag"
    email = "viktor.haag@gmail.com"

[outputs]
    home = ["HTML", "RSS"]
    page = ["HTML"]
    section = ["HTML"]
    taxonomy = ["HTML"]
    term = ["HTML"]

[params]
    badge_image = "https://www.gravatar.com/avatar/5afee2f4902e5bbf78c8dc03d1c96ee0"
    mainSections = [ "posts" ]

[permalinks]
    posts = "/:year/:month/:slug/"

[markup]
    [markup.goldmark]
        [markup.goldmark.parser]
            autoHeadingIDType = "blackfriday"
        [markup.goldmark.renderer]
            unsafe = true

[security]
    enableInlineShortcodes = false
    [security.exec]
       allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^rst2html.py$', '^postcss$']
       osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

    [security.funcs]
       getenv = ['^HUGO_']

    [security.http]
       methods = ['(?i)GET|POST']
       urls = ['.*']
