---
title: "Introduction"
---

This campaign guide contains information about the ongoing old-timey fantasy
games^[Old-time fantasy games laregly means games derived or remixed or built on
the chassis of "the original edition(s) of the world's most popular RPG".] set
in the lands east of the Imperial walled fortress town called Eagle Pass. Eagle
Pass is the eastern-most settlement in The Empire. Several generations ago,
under the ministrations of the mad Padishah Emperor Darius the Just, the Empire
was forming a strong position extended from Eagle Pass. Then Darius was …
removed from power. In the resulting disarray, the Empire suddenly had to
contend with solidifying its military positions on borders not in the east. Now,
things east of Eagle Pass are a mostly lawless wilderness: an opportunity for
adventure, fame, and glory. There still remain a few hardy villages and farms in
the woods and hills near to Eagle Pass, homesteaded by generations of Imperial
citizens, too stubborn to leave their patch. Their trade, and even trade from
native barbarian tribes-folk, has kept the modest market in Eagle Pass a going
concern.

Despite the empire’s fitful present in the region, they were not the first
civilized people to inhabit the east marches. Although now mostly ruled over by
beast-folk and barbaric tribes, at one point in the distant past, these lands
were within the dominion of the ancient Eld who were powerful, well versed in
the arcane, decadent, corrupt, and very, very fond of a style of architecture
that penetrated deep underground.
